resource_types:
- name: helloworld
  type: docker-image
  source:
    repository: surendharselvakumar/helloworld
    # set repo of your helloworld resource
    # or use my helloworld resource
    # repository: thehandsomezebra/concourse-resourcetype-helloworld

resources:
- name: helloworld
  type: helloworld
  check_every: 1s  
  
- name: repo
  type: git
  source:
    uri: https://github.com/SurenPonnusamy/helloworld-concourse
    branch: main
    private_key: ((private_key))
  
- name: docker-resource-type
  type: registry-image
  source: 
    repository: docker.io/surendharselvakumar/helloworld
    username: surendharselvakumar
    password: Suren2302%
    tag: latest  

jobs:      
- name: build-docker-image
  plan:
  - get: repo
    trigger: true
  - task: build-docker-resource-type
    privileged: true
    params:
      DOCKERFILE: Dockerfile
    config: 
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: repo
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: docker-resource-type
    params:
      image: image/image.tar  
      
- name: hello-job
  plan:
  - get: helloworld
    trigger: true
  - task: input-type    
    params:
      greeting: "Hello, from input"
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.io/surendharselvakumar/helloworld
          tag: latest
      run:
        path: ls
  - put: helloworld
    resource: helloworld
    inputs:
         - helloworld
    params:
      greeting: "Hey y'all!"