#!/bin/bash
echo '[{ "revision": "N/A",  "message": "The check script says Hello World!" }]'
set -eu
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo "Echo says hi from the out script!" >&2

source=$1

if [[ -z "$source" ]]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

export TMPDIR=${TMPDIR:-/tmp/check}
mkdir -p "${TMPDIR}"

payload=$(mktemp "$TMPDIR/resource-request.XXXXXX")
cat > "$payload" <&0

# greeting=$(jq -r '.params.greeting // ""' < "$payload")
params=$(jq -r '.source' < "$payload")
# echo "Param greeting says: $greeting" >&2
echo "Param greeting says: $params" >&2