#!/bin/bash
echo '[{ "revision": "N/A",  "message": "The check script says Hello World!" }]'
export TMPDIR=${TMPDIR:-/tmp/check}
mkdir -p "${TMPDIR}"

payload=$(mktemp "$TMPDIR/resource-request.XXXXXX")
date > $payload
cat $payload